# Generated by Django 2.1.3 on 2019-05-16 02:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appartenir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'appartenir',
            },
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('numexport', models.IntegerField(primary_key=True, serialize=False)),
                ('dateexport', models.DateField()),
                ('fruitexport', models.CharField(max_length=20)),
                ('sizeexport', models.IntegerField()),
                ('nbpalletexport', models.IntegerField()),
            ],
            options={
                'db_table': 'export',
            },
        ),
        migrations.CreateModel(
            name='Exporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numexport', models.ForeignKey(db_column='numexport', on_delete=django.db.models.deletion.CASCADE, to='fruitCoop.Export')),
            ],
            options={
                'db_table': 'exporter',
            },
        ),
        migrations.CreateModel(
            name='Exportform',
            fields=[
                ('numform', models.IntegerField(primary_key=True, serialize=False)),
                ('nbfruitform', models.IntegerField()),
                ('fruitform', models.CharField(max_length=20)),
                ('brixform', models.IntegerField()),
                ('parcelleform', models.CharField(max_length=10)),
                ('maturityform', models.CharField(max_length=5)),
                ('numexport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruitCoop.Export')),
            ],
            options={
                'db_table': 'exportform',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('nummember', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstnamemember', models.CharField(max_length=50)),
                ('lastnamemember', models.CharField(max_length=50)),
                ('birthdaydatemember', models.DateField()),
                ('telephonemember', models.CharField(max_length=15)),
                ('postalcodemember', models.IntegerField()),
                ('citymember', models.CharField(max_length=30)),
                ('address1member', models.CharField(max_length=40)),
                ('address2member', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'db_table': 'member',
            },
        ),
        migrations.CreateModel(
            name='Remplir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datecoliser', models.DateTimeField()),
                ('numexportform', models.ForeignKey(db_column='numexportform', on_delete=django.db.models.deletion.CASCADE, to='fruitCoop.Exportform')),
                ('nummember', models.ForeignKey(db_column='nummember', on_delete=django.db.models.deletion.CASCADE, to='fruitCoop.Member')),
            ],
            options={
                'db_table': 'remplir',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('numroom', models.IntegerField(primary_key=True, serialize=False)),
                ('nameroom', models.CharField(max_length=30)),
                ('postalcoderoom', models.IntegerField()),
                ('cityroom', models.CharField(max_length=30)),
                ('address1room', models.CharField(max_length=40)),
                ('address2room', models.CharField(blank=True, max_length=40)),
                ('capacityroom', models.IntegerField()),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('numslot', models.IntegerField(primary_key=True, serialize=False)),
                ('begindateslot', models.DateTimeField(verbose_name='date debut')),
                ('enddateslot', models.DateTimeField(verbose_name='date fin')),
                ('nbpalletslot', models.IntegerField()),
                ('fruitslot', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'slot',
            },
        ),
        migrations.AddField(
            model_name='exportform',
            name='nummember',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fruitCoop.Member'),
        ),
        migrations.AddField(
            model_name='exporter',
            name='nummember',
            field=models.ForeignKey(db_column='nummember', on_delete=django.db.models.deletion.CASCADE, to='fruitCoop.Member'),
        ),
        migrations.AddField(
            model_name='appartenir',
            name='nummember',
            field=models.ForeignKey(db_column='nummember', on_delete=django.db.models.deletion.CASCADE, to='fruitCoop.Member'),
        ),
        migrations.AddField(
            model_name='appartenir',
            name='numroom',
            field=models.ForeignKey(db_column='numroom', on_delete=django.db.models.deletion.CASCADE, to='fruitCoop.Room'),
        ),
        migrations.AlterUniqueTogether(
            name='remplir',
            unique_together={('nummember', 'numexportform')},
        ),
        migrations.AlterUniqueTogether(
            name='exporter',
            unique_together={('numexport', 'nummember')},
        ),
        migrations.AlterUniqueTogether(
            name='appartenir',
            unique_together={('numroom', 'nummember')},
        ),
    ]
