# Generated by Django 2.1.3 on 2019-05-16 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fruitCoop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remplir',
            name='datecoliser',
        ),
        migrations.AlterField(
            model_name='export',
            name='dateexport',
            field=models.DateField(verbose_name='date export'),
        ),
        migrations.AlterField(
            model_name='export',
            name='numexport',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
